# Generated by Django 2.0.4 on 2018-04-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocorn', '0003_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(help_text='Introduzca el nombre del actor', max_length=100)),
                ('lastName', models.CharField(help_text='Introduzca el apellido del actor', max_length=100)),
            ],
        ),
    ]
