# Generated by Django 2.0.4 on 2018-04-17 20:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videocorn', '0004_actor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='ID unico de esta película.', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('trailer', models.TextField(help_text='Enter movie trailer URL', max_length=1000)),
                ('overview', models.TextField(help_text='Enter a brief summary of the movie', max_length=1000, null=True)),
                ('director', models.CharField(max_length=100, null=True)),
                ('cover', models.TextField(help_text='Enter movie cover URL', max_length=1000, null=True)),
                ('cast', models.ManyToManyField(help_text='Seleccione los actores que parcitipan en esta pelicula.', null=True, to='videocorn.Actor')),
                ('genre', models.ManyToManyField(help_text='Seleccione un genero para esta pelicula.', null=True, to='videocorn.Genre')),
                ('score', models.ManyToManyField(help_text='Seleccione una valoracion para esta pelicula.', null=True, to='videocorn.Score')),
                ('year', models.ManyToManyField(help_text='Seleccione el año de estreno de esta pelicula.', null=True, to='videocorn.Year')),
            ],
        ),
    ]
