# Generated by Django 2.0.4 on 2018-04-17 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocorn', '0005_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los actores que parcitipan en esta pelicula.', null=True, to='videocorn.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='cover',
            field=models.TextField(blank=True, help_text='Enter movie cover URL', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, help_text='Seleccione el director de esta pelicula.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Seleccione un genero para esta pelicula.', null=True, to='videocorn.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(blank=True, help_text='Enter a brief summary of the movie', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.ManyToManyField(blank=True, help_text='Seleccione una valoracion para esta pelicula.', null=True, to='videocorn.Score'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Seleccione titulo de esta pelicula.', max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.ManyToManyField(blank=True, help_text='Seleccione el año de estreno de esta pelicula.', null=True, to='videocorn.Year'),
        ),
    ]
