# Generated by Django 2.0.4 on 2018-04-17 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videocorn', '0006_auto_20180417_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, help_text='Seleccione los actores que parcitipan en esta pelicula.', to='videocorn.Actor'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Seleccione un genero para esta pelicula.', to='videocorn.Genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='score',
            field=models.ManyToManyField(blank=True, help_text='Seleccione una valoracion para esta pelicula.', to='videocorn.Score'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.ManyToManyField(blank=True, help_text='Seleccione el año de estreno de esta pelicula.', to='videocorn.Year'),
        ),
    ]
