# Generated by Django 2.0.4 on 2018-05-13 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videocorn', '0009_auto_20180512_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='score',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
    ]
