# Generated by Django 2.0.4 on 2018-05-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('videocorn', '0010_auto_20180513_0226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('trailer', models.TextField(max_length=1000)),
                ('overview', models.TextField(blank=True, max_length=1000, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('cover', models.TextField(blank=True, max_length=1000, null=True)),
                ('cast', models.ManyToManyField(blank=True, to='videocorn.Actor')),
                ('genre', models.ManyToManyField(blank=True, to='videocorn.Genre')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('stars', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('date', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='score',
            field=models.ManyToManyField(blank=True, to='videocorn.Score'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.ManyToManyField(blank=True, to='videocorn.Year'),
        ),
    ]
